name: Bellucci Digital
favicon: null
layout_spectrum: 0.3477521638851613
typography_spectrum: 0.41588403983041644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.44106387067586184
  lightness: 0.5194161124527454
  saturation: 0.28691136511042714
  rhythmicContrast: 0.8697329682763666
purpose: []
