name: Bellucci Digital
favicon: null
layout_spectrum: 0.50674
typography_spectrum: 0.50258
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a1b0d7'
    - '#c39e8a'
    - '#a78273'
    - '#7b6461'
    - '#ecceb3'
  brandStrength: 0.44106387067586184
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
